### ISSUE TITLE
关于字数过多导致结果中断的问题

### ISSUE THREAD

**Issue by 3kinglee** [AIOS-club/aios.chat#104]
当上下文字数超过gpt限制时，回复会中断，是否能加入自动计算token数然后自动丢弃超过token数的部分上下文的功能

**Comment by iwgyyyy** [comment]
可尝试一下[plus]版本(https://plus.aios.chat)，开源版本后续会更新

**Comment by iwgyyyy** [comment]
可尝试一下[plus](https://plus.aios.chat)版本，开源版本后续会更新上
