### ISSUE TITLE
@binjie 你好意思吗

### ISSUE THREAD

**Issue by yooyea** [AIOS-club/aios.chat#105]
你 chatgpt 项目 fork 了一份老旧版本的

自己在那更新前后端代码一直不同步上传到 github 上来

现在这版看更新时间都是几个月前了，你拿这 3k 的 star 好意思吗？

项目你还把 issue 给关了，扪心自问你是做开源的人吗？

麻烦你要么关闭项目隐藏 github 入口，要么同步代码

别拿了好处不干事行么

@binjie09

**Comment by binjie09** [comment]
前端除了捐赠按钮部分没有任何改动了,您目前看到的代码就是我前端部署使用的最新的代码了,后端代码一开始就是独立开发,没有使用原作者的,所以不开源也符合开源协议呢~

**Comment by yooyea** [comment]
拿前端空壳开源揽 Star，核心后台闭源，6
