### ISSUE TITLE
和你直播时候一样的错误……

### ISSUE THREAD

**Issue by withcandle** [AIOS-club/aios.chat#17]
> 
![34476AA2-C147-42AC-9263-E92659156DF3](https://user-images.githubusercontent.com/117502533/225978325-89a7469c-fcdb-418c-942e-efada7e99dcd.jpeg)
Api key肯定是可以用的

**Comment by halooojustin** [comment]
openai的接口在国内是被墙了。你可能需要代理一下网络

同时，我们后面需要再提供一个跟 openai 兼容的接口

**Comment by withcandle** [comment]
已放在国外的服务器上也需要反代吗？谢谢

**Comment by halooojustin** [comment]
放在国外服务器，不需要的，如果还有问题，可以提供截图看看

**Comment by withcandle** [comment]
运行了，但为啥每次只能回答一个问题，第二个问题回答了又会回退告诉你：请稍后重试

![83D9505F-FFC5-4FF1-AB21-0B2F9B38B5BA](https://user-images.githubusercontent.com/117502533/226111178-fbef19e9-dc63-4a91-bcc9-2e30e626d916.jpeg)
![D8D04BCE-AE8F-4665-92FB-5D045537603D](https://user-images.githubusercontent.com/117502533/226111181-a85a9fd1-c1a7-4a12-afba-6ec9a110fc79.jpeg)
