### ISSUE TITLE
报错呀，还是超时，key肯定是没问题的

### ISSUE THREAD

**Issue by Hai-kaizhi** [AIOS-club/aios.chat#18]
游览器提示错误：
Access to XMLHttpRequest at 'http://localhost:3000/aios-chat' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
:3000/aios-chat:1 

Uncaught TypeError: Cannot read properties of null (reading 'contentWindow')

服务器：
Error: connect ETIMEDOUT 108.160.166.142:443

**Comment by iwgyyyy** [comment]
openai的接口在国内是被墙了。你可能需要代理一下网络
