### ISSUE TITLE
请问应该如何配置# API_HOST

### ISSUE THREAD

**Issue by HarrySxk** [AIOS-club/aios.chat#20]
示例中是
# API_HOST
VITE_API_HOST='http://localhost:3000/aios-chat'

然而我的node.js安装完后是
http://localhost:5173
并且我在开源目录下无法找到aios-chat文件夹相关内容。
![image](https://user-images.githubusercontent.com/128143266/226104715-3ba9b352-1c14-4f8e-98f4-f0bbcc01596f.png)

多谢指教。

**Comment by HarrySxk** [comment]
补充一下，api-key确认可以用，墙的问题也解决了。

**Comment by iwgyyyy** [comment]
5173是你vite项目的端口。后端服务的端口一般为3000，如果你的端口没被占用的话。可以先将VITE_API_HOST设置为http://localhost:3000/aios-chat 试一下。如果不行。就看下你的后端服务端口是多少 改一下对应的VITE_API_HOST环境变量的端口号就好了

**Comment by TaTapark** [comment]
请问有key之外 还需要魔法梯子吗？
