### ISSUE TITLE
node.js运行时报错

### ISSUE THREAD

**Issue by HarrySxk** [AIOS-club/aios.chat#21]
nom run dev报错信息如下，哪位大佬帮忙看看怎么解决。
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/128143266/226109965-e84c08f9-a1a5-4832-a37f-56f95ec19d1e.png">

**Comment by iwgyyyy** [comment]
看一下server目录下的node_modules里面有没有装上koa。

**Comment by TaTapark** [comment]
mac本 sudo 以下依赖安装命令
