### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by 011-Tao** [AIOS-club/aios.chat#29]
![Snipaste_2023-03-22_14-34-44](https://user-images.githubusercontent.com/54564917/226823395-59940d94-a61b-4faa-a1e0-cfd4866830b2.png)
大佬，key 是对的啊， 这个怎么解决呢？

**Comment by iwgyyyy** [comment]
有开代理吗

**Comment by 011-Tao** [comment]
开了

**Comment by 011-Tao** [comment]
> ![Snipaste_2023-03-22_14-34-44](https://user-images.githubusercontent.com/54564917/226823395-59940d94-a61b-4faa-a1e0-cfd4866830b2.png) 大佬，key 是对的啊，代理也开了， 这个怎么解决呢？

**Comment by iwgyyyy** [comment]
> > ![Snipaste_2023-03-22_14-34-44](https://user-images.githubusercontent.com/54564917/226823395-59940d94-a61b-4faa-a1e0-cfd4866830b2.png) 大佬，key 是对的啊，代理也开了， 这个怎么解决呢？

![image](https://user-images.githubusercontent.com/55680034/227720051-cc8467a6-a422-4015-8a24-6468f375af83.png)
你的前端路径是不是不太正确

**Comment by feikoooo** [comment]
海外服务器部署也是这个情况，请问题怎么处理呀！！！
